### ISSUE TITLE
Allow for configuration of unix socket path

### ISSUE THREAD

**Issue by jn9e9** [parallaxsecond/parsec-client-go#19]
currently fixed to /run/parsec/parsec.sock, should be modifiable, possibly config file support?

**Comment by hug-dev** [comment]
I think defaulting it to `/run/parsec/parsec.sock` is good for now. The path is fixed so that clients do not need a discovery mechanism to know at what path is the genuine Parsec service on their machine. Also helps to respect some of the threat model mitigations.

We thought about such mechanisms in parallaxsecond/parsec-client-rust#37

However, agree that it should be possible to change it programmatically with a method, for testing for example.

**Comment by hug-dev** [comment]
Actually, we went ahead and agreed that this change was needed on the Rust client. So I guess the Go client should follow a similar way and allow configuring the endpoint through the `PARSEC_SERVICE_EDNPOINT` environment variable!

**Comment by hug-dev** [comment]
And the documentation about that is now [here](https://parallaxsecond.github.io/parsec-book/parsec_client/api_overview.html#service-discovery) 😃 !
