### ISSUE TITLE
CI Test no longer works

### ISSUE THREAD

**Issue by jn9e9** [parallaxsecond/parsec-client-go#40]
Since april, parsec service and related CI test docker file have moved on, which means that go client ci test scripts cannot compile parsec service and likely won't work anyway.

**Comment by ionut-arm** [comment]
Copied from #41:

I think the build is failing because we added a new provider to Parsec which needs a submodule to be initialised, so you need to do a `git submodule update --init` before [building the service](https://github.com/parallaxsecond/parsec-client-go/blob/main/e2etest/provider_cfg/all/Dockerfile#L21). You also need to include `direct-authenticator` as a feature in that build command. I'll review the actual PR now.
